
-- DDL SQL -- 
CREATE TABLE Taco (
	ID INT AUTO_INCREMENT PRIMARY KEY, 
	NAME VARCHAR(250) NOT NULL,
	CREATE_DATE TIMESTAMP NOT NULL,
	UPDAT_DATE TIMESTAMP NOT NULL
);

CREATE TABLE Ingredient (
	ID INT AUTO_INCREMENT PRIMARY KEY, 
	NAME VARCHAR(250) NOT NULL,
	CREATE_DATE TIMESTAMP NOT NULL,
	UPDAT_DATE TIMESTAMP NOT NULL
);

CREATE TABLE Orders (
	ID INT AUTO_INCREMENT PRIMARY KEY, 
	NAME VARCHAR(250) NOT NULL,
	STREET VARCHAR(250),
	CITY VARCHAR(250),
	STATE VARCHAR(250),
	ZIP VARCHAR(250),
	CC_NUMBER VARCHAR(250),
	CC_EXPIRATION VARCHAR(250),
	CC_CVV VARCHAR(250),
	CREATE_DATE TIMESTAMP NOT NULL,
	UPDAT_DATE TIMESTAMP NOT NULL
);

CREATE TABLE Taco_Orders (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TACO_ID INT NOT NULL,
	ORDER_ID INT NOT NULL,
	CREATE_DATE TIMESTAMP NOT NULL,
	UPDAT_DATE TIMESTAMP NOT NULL,
	CONSTRAINT FK_Taco_Orders_Taco FOREIGN KEY (TACO_ID) REFERENCES TACO(ID),
	CONSTRAINT FK_Taco_Orders_Orders FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID)
);

CREATE TABLE Taco_Ingredient (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TACO_ID INT NOT NULL,
	INGREDIENT_ID INT NOT NULL,
	CREATE_DATE TIMESTAMP NOT NULL,
	UPDAT_DATE TIMESTAMP NOT NULL,
	CONSTRAINT FK_Taco_Ingredient_Taco FOREIGN KEY (TACO_ID) REFERENCES TACO(ID),
	CONSTRAINT FK_Taco_Ingredient_Ingredient FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(ID)
);